# serverless.yml
service: test

plugins:
  - serverless-reqvalidator-plugin
  - '@ublend-npm/serverless-aws-documentation'

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  region: eu-west-1

package:
  include:
    - src/**
    - api.docs.yaml
    - package.json


custom:
  documentation:
    openapi: true
    api: ${file(./api.docs.yaml)}

functions:
  addMessage:
    handler: index.addMessage # required, handler set in AWS Lambda
    description: Add Message
    events:
      - http:
          path: /message
          method: POST
          reqValidatorName: 'onlyBody'


resources:
  Resources:
    onlyBody:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'onlyBody'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
